### ISSUE TITLE
Mechanism to set the random seed is missing

### ISSUE THREAD

**Issue by jake-arkinstall** [HQSquantumsimulations/qoqo-quest#189]
I'm looking for a method to set the random seed used for measurements in order to run reproducible simulations.

In the quest_sys documentation, there are some mentions of using `seedQuEST` to set a seed. However, this is currently missing from the rust wrapper.

**Comment by nfwvogt** [comment]
Yes, we haven't implemented that feature on the rust side yet, but I agree it is useful. We will  try to add it to the next release.

**Comment by dberthault** [comment]
Hi, with the version `0.14.4` you can now set the random seed of the backend with the `set_random_seed` method, here is an example:

```py
from qoqo import Circuit, operations as ops
from qoqo_quest import Backend

backend = Backend(3)

backend.set_random_seed([1234, 456789])

circuit = Circuit()
circuit += ops.DefinitionBit("ro", 4, True)
circuit += ops.Hadamard(0)
circuit += ops.Hadamard(1)
circuit += ops.Hadamard(2)
circuit += ops.MeasureQubit(0, "ro", 0)
circuit += ops.MeasureQubit(1, "ro", 1)
circuit += ops.MeasureQubit(2, "ro", 2)

print(backend.run_circuit(circuit))
```
The seed should be a list of ints

Closing this issue, feel free to re-open it if there is any problem with the feature
